[package]
name = "rust-rocket-template"
version = "0.1.0"
authors = ["ATechnoHazard <amolele@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.5", features = ["postgres"] }
dotenv = "0.15.0"
